package com.ryuqq.marketplace.domain.brand.vo;

/**
 * Alias Source Type Enum
 *
 * <p><strong>소스 타입</strong>:</p>
 * <ul>
 *   <li>SELLER - 셀러 입력</li>
 *   <li>EXTERNAL_MALL - 외부몰 연동</li>
 *   <li>LEGACY - 레거시 데이터</li>
 *   <li>MANUAL - 수동 입력</li>
 *   <li>SYSTEM - 시스템 자동 생성</li>
 * </ul>
 *
 * @author development-team
 * @since 1.0.0
 */
public enum AliasSourceType {
    SELLER,
    EXTERNAL_MALL,
    LEGACY,
    MANUAL,
    SYSTEM;

    /**
     * 자동 생성 타입 여부 확인
     *
     * @return SYSTEM이면 true
     */
    public boolean isAutoGenerated() {
        return this == SYSTEM;
    }

    /**
     * 수동 입력 타입 여부 확인
     *
     * @return MANUAL이면 true
     */
    public boolean isManual() {
        return this == MANUAL;
    }

    /**
     * 문자열로부터 AliasSourceType 찾기
     *
     * @param value 문자열 값
     * @return AliasSourceType
     * @throws IllegalArgumentException 일치하는 타입이 없는 경우
     */
    public static AliasSourceType fromString(String value) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException("AliasSourceType 값은 null이거나 빈 문자열일 수 없습니다.");
        }

        try {
            return valueOf(value.trim().toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("유효하지 않은 AliasSourceType 값입니다: " + value);
        }
    }
}
