-- 레거시-내부 셀러 ID 매핑 테이블
-- N:1 매핑 가능 (레거시에서 같은 셀러를 여러 계정으로 운영하는 케이스 존재)
-- 예: luxurydb 28(setof), 31(trexi) → market 25(trexi)
CREATE TABLE `legacy_seller_id_mapping` (
    `id`                 BIGINT       NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `legacy_seller_id`   BIGINT       NOT NULL COMMENT 'luxurydb seller.seller_id',
    `internal_seller_id` BIGINT       NOT NULL COMMENT 'market sellers.id',
    `seller_name`        VARCHAR(100) NOT NULL COMMENT '매칭 검증용 셀러명',
    `created_at`         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    `updated_at`         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_legacy_seller_id` (`legacy_seller_id`),
    KEY `idx_internal_seller_id` (`internal_seller_id`),
    KEY `idx_seller_name` (`seller_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='레거시-내부 셀러 ID 매핑';

-- 기존 하드코딩 매핑 데이터 시드 (LegacyConversionPreResolver.LEGACY_SELLER_ID_MAP 기준)
-- legacy_seller_id UNIQUE, internal_seller_id 중복 허용
-- 참고: legacy 1(admin) 은 매핑에서 제외 (admin → skip)
-- 참고: legacy 28(setof), 31(trexi) → market 25 (같은 셀러, N:1)
-- 참고: market 28(룩플러스)에 매핑된 레거시 없음
INSERT INTO `legacy_seller_id_mapping` (`legacy_seller_id`, `internal_seller_id`, `seller_name`) VALUES
    (2, 1, 'bellitalia'),
    (4, 2, 'bino2345'),
    (5, 3, 'buono_dj'),
    (6, 4, 'carino'),
    (7, 5, 'ccapsule1'),
    (8, 6, 'dmont'),
    (9, 7, 'fixedone'),
    (10, 8, 'italiagom'),
    (11, 9, 'L-ONE'),
    (12, 10, 'LIKEASTAR'),
    (13, 11, 'LOUI'),
    (14, 12, 'LUXNHOLIC'),
    (15, 13, 'maisonparco'),
    (16, 14, 'myaria'),
    (17, 15, 'noblecoco_'),
    (18, 16, 'RUNNERSELL'),
    (19, 17, 'SUBIR'),
    (20, 18, 'thefactor2'),
    (22, 22, 'THEGRANDE'),
    (23, 19, 'viaitalia'),
    (24, 20, 'VIVIANO'),
    (25, 21, 'wdrobe'),
    (26, 23, 'winsome1978'),
    (27, 24, 'winusavenue'),
    (28, 25, 'setof'),
    (29, 26, 'ALLIWANT'),
    (30, 27, 'UPSET'),
    (31, 25, 'trexi'),
    (34, 29, 'BONTANO'),
    (35, 30, 'AmericanNeedle'),
    (36, 31, 'Bensimon'),
    (37, 32, 'Timberland'),
    (40, 34, 'daomcor'),
    (42, 35, 'wingsfoot'),
    (43, 36, 'footmart'),
    (56, 37, 'IKNOWK'),
    (57, 38, 'origo'),
    (58, 39, 'WEOinc'),
    (59, 40, 'BESTON'),
    (60, 41, 'SOSOHANBIT'),
    (61, 42, 'marvelcollection'),
    (62, 43, 'GMLS'),
    (63, 44, 'MEYER'),
    (64, 45, 'Cardmon'),
    (65, 46, 'keshop'),
    (66, 47, 'koreaboardgames'),
    (67, 48, 'carif'),
    (68, 49, 'bumkins'),
    (69, 50, 'BLITZWAY'),
    (70, 51, 'gaia'),
    (71, 52, 'Asolution'),
    (72, 53, 'marhenj'),
    (73, 54, 'megoskorea'),
    (74, 55, 'klepton'),
    (75, 56, 'RSCholdings'),
    (76, 57, 'GOODORVERYGOOD'),
    (77, 58, 'backpacker'),
    (78, 59, 'CLAPS'),
    (79, 60, 'THEART'),
    (80, 61, 'NationalGeographicMobileAccessory'),
    (81, 62, 'MAYTON'),
    (82, 63, 'oneplusdesign'),
    (83, 64, 'ModernHouse'),
    (84, 65, 'LILFANT'),
    (85, 66, 'goldpang'),
    (86, 67, 'Gosty'),
    (87, 68, 'SCRUB DADDY'),
    (88, 69, 'NLIZE'),
    (89, 70, 'sweetjoy'),
    (90, 71, 'MadeInKorea2025'),
    (91, 72, 'molancano'),
    (92, 73, 'TINYVILLE'),
    (93, 74, 'slko'),
    (94, 75, 'HOHOPE1977');
