CREATE TABLE IF NOT EXISTS image_transform_outboxes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    source_image_id BIGINT NOT NULL COMMENT '소스 이미지 ID',
    source_type VARCHAR(30) NOT NULL COMMENT 'PRODUCT_GROUP_IMAGE, DESCRIPTION_IMAGE',
    uploaded_url VARCHAR(500) NOT NULL COMMENT '업로드된 CDN URL',
    variant_type VARCHAR(30) NOT NULL COMMENT 'SMALL_WEBP, MEDIUM_WEBP, LARGE_WEBP, ORIGINAL_WEBP',
    transform_request_id VARCHAR(100) NULL COMMENT 'FileFlow 변환 요청 ID',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    retry_count INT NOT NULL DEFAULT 0,
    max_retry INT NOT NULL DEFAULT 3,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    processed_at TIMESTAMP NULL,
    error_message VARCHAR(1000) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ito_idempotency_key (idempotency_key),
    INDEX idx_ito_status (status),
    INDEX idx_ito_source (source_type, source_image_id),
    INDEX idx_ito_transform_request (transform_request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
