CREATE TABLE IF NOT EXISTS product_group_inspection_outboxes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    product_group_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    inspection_result_json TEXT NULL,
    total_score INT NULL,
    passed TINYINT(1) NULL,
    retry_count INT NOT NULL DEFAULT 0,
    max_retry INT NOT NULL DEFAULT 3,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    processed_at TIMESTAMP NULL,
    error_message VARCHAR(1000) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_pgio_idempotency_key (idempotency_key),
    INDEX idx_pgio_status_created (status, created_at),
    INDEX idx_pgio_status_updated (status, updated_at),
    INDEX idx_pgio_product_group (product_group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
