CREATE TABLE IF NOT EXISTS product_profiles (
    id BIGINT NOT NULL AUTO_INCREMENT,
    product_group_id BIGINT NOT NULL,
    profile_version INT NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    expected_analysis_count INT NOT NULL DEFAULT 3,
    completed_analysis_count INT NOT NULL DEFAULT 0,
    completed_analysis_types VARCHAR(100) NULL COMMENT 'CSV: DESCRIPTION,OPTION,NOTICE',
    extracted_attributes_json TEXT NULL,
    option_suggestions_json TEXT NULL,
    notice_suggestions_json TEXT NULL,
    decision_type VARCHAR(20) NULL,
    overall_confidence DOUBLE NULL,
    decision_reasons_json TEXT NULL,
    decision_at DATETIME(6) NULL,
    raw_analysis_json TEXT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    analyzed_at DATETIME(6) NULL,
    expired_at DATETIME(6) NULL,
    error_message VARCHAR(1000) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    INDEX idx_pp_product_group (product_group_id),
    INDEX idx_pp_status_created (status, created_at),
    INDEX idx_pp_product_group_version (product_group_id, profile_version),
    INDEX idx_pp_expired (expired_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
