CREATE TABLE inbound_products (
    id                        BIGINT AUTO_INCREMENT PRIMARY KEY,
    external_source_id        BIGINT NOT NULL,
    external_product_code     VARCHAR(255) NOT NULL,
    product_name              VARCHAR(500) NOT NULL,
    external_brand_code       VARCHAR(255),
    external_category_code    VARCHAR(255),
    internal_brand_id         BIGINT,
    internal_category_id      BIGINT,
    internal_product_group_id BIGINT,
    seller_id                 BIGINT NOT NULL,
    regular_price             INT NOT NULL DEFAULT 0,
    current_price             INT NOT NULL DEFAULT 0,
    option_type               VARCHAR(50) NOT NULL,
    status                    VARCHAR(50) NOT NULL,
    description_html          LONGTEXT,
    raw_payload               JSON,
    created_at                DATETIME(6) NOT NULL,
    updated_at                DATETIME(6) NOT NULL,
    UNIQUE KEY uk_source_product (external_source_id, external_product_code),
    INDEX idx_status (status),
    INDEX idx_internal_product_group (internal_product_group_id),
    INDEX idx_seller (seller_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
