-- inbound_orders 테이블
CREATE TABLE IF NOT EXISTS inbound_orders (
    id BIGINT NOT NULL AUTO_INCREMENT,
    sales_channel_id BIGINT NOT NULL,
    shop_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    external_order_no VARCHAR(100) NOT NULL,
    external_ordered_at TIMESTAMP NOT NULL,
    buyer_name VARCHAR(100) NOT NULL,
    buyer_email VARCHAR(255) NULL,
    buyer_phone VARCHAR(20) NULL,
    payment_method VARCHAR(50) NULL COMMENT '결제수단 (CARD, BANK_TRANSFER 등)',
    total_payment_amount INT NOT NULL DEFAULT 0 COMMENT '주문 총 결제금액',
    paid_at TIMESTAMP NULL COMMENT '결제 완료 시점',
    status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    internal_order_id VARCHAR(36) NULL COMMENT '변환된 내부 Order ID',
    failure_reason VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE INDEX uk_inbound_orders_channel_ext (sales_channel_id, external_order_no),
    INDEX idx_inbound_orders_status (status),
    INDEX idx_inbound_orders_seller (seller_id),
    INDEX idx_inbound_orders_external_ordered (sales_channel_id, external_ordered_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- inbound_order_items 테이블
CREATE TABLE IF NOT EXISTS inbound_order_items (
    id BIGINT NOT NULL AUTO_INCREMENT,
    inbound_order_id BIGINT NOT NULL,
    external_product_id VARCHAR(100) NOT NULL,
    external_option_id VARCHAR(100) NULL,
    external_product_name VARCHAR(500) NULL,
    external_option_name VARCHAR(500) NULL,
    external_image_url VARCHAR(1000) NULL,
    unit_price INT NOT NULL DEFAULT 0,
    quantity INT NOT NULL DEFAULT 1,
    total_amount INT NOT NULL DEFAULT 0,
    discount_amount INT NOT NULL DEFAULT 0,
    payment_amount INT NOT NULL DEFAULT 0,
    receiver_name VARCHAR(100) NOT NULL,
    receiver_phone VARCHAR(20) NULL,
    receiver_zipcode VARCHAR(10) NULL,
    receiver_address VARCHAR(500) NULL,
    receiver_address_detail VARCHAR(500) NULL,
    delivery_request VARCHAR(500) NULL,
    resolved_product_group_id BIGINT NULL,
    resolved_product_id BIGINT NULL,
    resolved_seller_id BIGINT NULL,
    resolved_brand_id BIGINT NULL,
    resolved_sku_code VARCHAR(50) NULL,
    mapped TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_inbound_order_items_order (inbound_order_id),
    INDEX idx_inbound_order_items_ext_product (external_product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
