CREATE TABLE setof_sync_outboxes (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    seller_id       BIGINT       NOT NULL,
    entity_id       BIGINT       NOT NULL,
    entity_type     VARCHAR(30)  NOT NULL,
    operation_type  VARCHAR(20)  NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    retry_count     INT          NOT NULL DEFAULT 0,
    max_retry       INT          NOT NULL DEFAULT 3,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    processed_at    TIMESTAMP(6) NULL,
    error_message   VARCHAR(1000) NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(100) NOT NULL,
    UNIQUE KEY uk_idempotency (idempotency_key),
    INDEX idx_status_created (status, created_at),
    INDEX idx_status_updated (status, updated_at),
    INDEX idx_seller_entity (seller_id, entity_type)
);
