package com.ryuqq.marketplace.domain.legacy.productgroup.vo;

/** 레거시(세토프) 원산지 enum. ISO 3166-1 alpha-2 코드 기반. */
public enum Origin {
    AE("United Arab Emirates"),
    AF("Afghanistan"),
    AL("Albania"),
    AM("Armenia"),
    AR("Argentina"),
    AT("Austria"),
    AU("Australia"),
    BA("Bosnia and Herzegovina"),
    BD("Bangladesh"),
    BE("Belgium"),
    BG("Bulgaria"),
    BO("Bolivia"),
    BR("Brazil"),
    BY("Belarus"),
    CA("Canada"),
    CH("Switzerland"),
    CL("Chile"),
    CM("Cameroon"),
    CN("China"),
    CO("Colombia"),
    CR("Costa Rica"),
    CS("Montenegro"),
    CU("Cuba"),
    CY("Cyprus"),
    CZ("Czechia"),
    DE("Germany"),
    DK("Denmark"),
    DM("Dominica"),
    DO("Dominican Republic"),
    DZ("Algeria"),
    EC("Ecuador"),
    EE("Estonia"),
    EG("Egypt"),
    ES("Spain"),
    FI("Finland"),
    FR("France"),
    GB("Great Britain"),
    GE("Georgia"),
    GR("Greece"),
    GU("Guam"),
    GT("Guatemala"),
    HK("Hong Kong"),
    HN("Honduras"),
    HR("Croatia"),
    HT("Haiti"),
    HU("Hungary"),
    ID("Indonesia"),
    IE("Ireland"),
    IL("Israel"),
    IN("India"),
    IR("Iran"),
    IS("Iceland"),
    IT("Italy"),
    JE("Jersey"),
    JM("Jamaica"),
    JO("Jordan"),
    JP("Japan"),
    KE("Kenya"),
    KG("Kyrgyzstan"),
    KH("Cambodia"),
    KM("Comoros"),
    KP("North Korea"),
    KR("South Korea"),
    KW("Kuwait"),
    KZ("Kazakhstan"),
    LA("Laos"),
    LB("Lebanon"),
    LK("Sri Lanka"),
    LR("Liberia"),
    LS("Lesotho"),
    LT("Lithuania"),
    LU("Luxembourg"),
    LV("Latvia"),
    LY("Libya"),
    MA("Morocco"),
    MC("Monaco"),
    MD("Moldova"),
    MF("Saint Martin"),
    MG("Madagascar"),
    MK("Macedonia"),
    ML("Mali"),
    MM("Myanmar"),
    MN("Mongolia"),
    MO("Macao"),
    MR("Mauritania"),
    MS("Montserrat"),
    MT("Malta"),
    MU("Mauritius"),
    MV("Maldives"),
    MW("Malawi"),
    MX("Mexico"),
    MY("Malaysia"),
    NC("New Caledonia"),
    NG("Nigeria"),
    NI("Nicaragua"),
    NL("Netherlands"),
    NO("Norway"),
    NP("Nepal"),
    NZ("New Zealand"),
    PE("Peru"),
    PH("Philippines"),
    PK("Pakistan"),
    PL("Poland"),
    PR("Puerto Rico"),
    PS("Palestine"),
    PT("Portugal"),
    PY("Paraguay"),
    QA("Qatar"),
    RO("Romania"),
    RS("Serbia"),
    RU("Russia"),
    SA("Saudi Arabia"),
    SC("Scotland"),
    SD("Sudan"),
    SE("Sweden"),
    SG("Singapore"),
    SI("Slovenia"),
    SK("Slovakia"),
    SL("Sierra Leone"),
    SM("San Marino"),
    SN("Senegal"),
    SO("Somalia"),
    SS("South Sudan"),
    SY("Syria"),
    TG("Togo"),
    TH("Thailand"),
    TL("East Timor"),
    TN("Tunisia"),
    TR("Turkey"),
    TW("Taiwan"),
    UA("Ukraine"),
    UG("Uganda"),
    UK("United Kingdom"),
    US("United States"),
    UY("Uruguay"),
    UZ("Uzbekistan"),
    VE("Venezuela"),
    VN("Vietnam"),
    ZA("South Africa"),
    ZM("Zambia"),
    ZZ("Other"),
    OTHER("Other");

    private final String description;

    Origin(String description) {
        this.description = description;
    }

    public String description() {
        return description;
    }
}
