package com.ryuqq.marketplace.domain.claimsync.vo;

/** 클레임 동기화 처리 결과 액션. */
public enum ClaimSyncAction {
    CANCEL_CREATED,
    CANCEL_APPROVED,
    CANCEL_COMPLETED,
    CANCEL_WITHDRAWN,
    REFUND_CREATED,
    REFUND_COLLECTING,
    REFUND_COLLECTED,
    REFUND_COMPLETED,
    REFUND_REJECTED,
    REFUND_HELD,
    REFUND_HOLD_RELEASED,
    EXCHANGE_CREATED,
    EXCHANGE_COLLECTING,
    EXCHANGE_COLLECTED,
    EXCHANGE_SHIPPING,
    EXCHANGE_COMPLETED,
    EXCHANGE_REJECTED,
    EXCHANGE_HELD,
    EXCHANGE_HOLD_RELEASED,
    SKIPPED
}
